vim.cmd('abb m func main()')
vim.cmd('abb r range')
vim.cmd('abb t type')
vim.cmd('abb s struct')
vim.cmd('abb f func')
vim.cmd('abb i int')
vim.cmd('abb p package')
vim.cmd('abb t type')
vim.cmd('abb c chan')
vim.cmd('abb e if err != nil')

vim.cmd('abb st string')
vim.cmd('abb re return')
vim.cmd('abb ln log.Println("')
vim.cmd('abb lf log.Printf("')
