
vim.cmd('abb apple Expense:Food:Fruit:Apple  ')
vim.cmd('abb avocado Expense:Food:Fruit:Avocado  ')
vim.cmd('abb banana Expense:Food:Fruit:Banana  ')
vim.cmd('abb orange Expense:Food:Fruit:Orange  ')
vim.cmd('abb celery Expense:Food:Spice:Celery  ')
vim.cmd('abb beans Expense:Food:Vegetable:Beans ')
vim.cmd('abb potato Expense:Food:Vegetable:Potato  ')
vim.cmd('abb corn Expense:Food:Vegetable:Corn  ')
vim.cmd('abb onion Expense:Food:Vegetable:Onion  ')
vim.cmd('abb potato Expense:Food:Vegetable:Potato  ')
vim.cmd('abb tomato Expense:Food:Vegetable:Tomato  ')
vim.cmd('abb cabbage Expense:Food:Vegetable:Cabbage  ')
vim.cmd('abb carrot Expense:Food:Vegetable:Carrot  ')
vim.cmd('abb broccoli Expense:Food:Vegetable:Broccoli  ')
vim.cmd('abb milk Expense:Food:Dairy:Milk  ')
vim.cmd('abb egg Expense:Food:Dairy:Egg  ')
vim.cmd('abb meat Expense:Food:Meat  ')
vim.cmd('abb spice Expense:Food:Spice  ')
vim.cmd('abb grain Expense:Food:Grain  ')
vim.cmd('abb snack Expense:Food:Snack  ')

vim.cmd('abb gas Expense:Transport:Gas  ')
vim.cmd('abb metro Expense:Transport:Metro  ')
vim.cmd('abb rental Expense:Transport:Rental  ')
vim.cmd('abb uber Expense:Transport:Uber  ')

vim.cmd('abb groc Expense:Food:Grocery  ')
vim.cmd('abb dining Expense:Food:Dining   ')
vim.cmd('abb beverage Expense:Food:Beverage  ')
vim.cmd('abb internet Expense:Rental:Internet  ')
vim.cmd('abb rental Expense:Rental:Principle  ')
vim.cmd('abb sub Expense:Subscription  ')

vim.cmd('abb joint Asset:Checking:Joint')
vim.cmd('abb tan Asset:Checking:Tangerine')
vim.cmd('abb rbc Asset:Checking:RBC')
vim.cmd('abb cibc Asset:Checking:CIBC')

vim.cmd('abb mt Liability:MasterCard:Tangerine')
vim.cmd('abb rv Liability:Visa:RBC')
vim.cmd('abb mc Liability:MasterCard:RBC')
vim.cmd('abb cv Liability:Visa:CIBC')

vim.cmd('abb mtl ; City: Montreal')
vim.cmd('abb todo ; TODO')

vim.cmd('abb c CAD')
vim.cmd('abb u USD')
